### ISSUE TITLE
Write an assembly guide

### ISSUE THREAD

**Issue by Aurelie-Mutschler** [echopen/PRJ-medtec_sigproc#34]
From the draft (word document) and images available for download in this issue, write a comprehensive assembly guide (in markdown) for 3.0.0 release.

Indicative due date : April 10th, 2017

Criteria to close the issue :
- Update the prototyping gitbook (https://echopen.gitbooks.io/echopen_prototyping/) with the assembly guide.
- To edit the gitbook, clone the repo : https://github.com/echopen/echopen_prototyping
- Edit the corresponding markdown file : stable/guide_hardware.md
- Make a pull request

**Comment by kelu124** [comment]
@Aurelie-Mutschler wrong board / wrong PRJ, isn't it? It should be on "echopen_prototyping" =)

**Comment by Aurelie-Mutschler** [comment]
Moved in echopen_prototyping !
